FROM tomcat:<%= image.version -%><%= image.variant.empty? ? "" : "-#{image.variant}" %>

<%= snippet('labels', binding) -%>

<%# snippet('docker-entrypoint', binding) -%>

<%= snippet('dockerize', binding) -%>

<%= snippet('tini', binding) -%>

ENTRYPOINT ["/tini", "--", "/docker-entrypoint.sh"]
CMD [ "init-loop" ]

